### ISSUE TITLE
Internet Explorer should be deprecated 

### ISSUE THREAD

**Issue by duorient** [umn-microsoft-automation/UMN-Google#37]
Can you make an update to line 231 of UMN-Google.psm1? Currently it's making an assumption that the system has IE installed. I'm trying to run this on a mac and IE is just not available. Thanks!

**Comment by travis-sobeck** [comment]
Unfortunately its not a simple fix because other browsers don't necessarily have com objects to call, so you need to launch a browser (and know where the binary is located) and capture resulting response to snag the authorization code.  We generally just use Get-GOAuthTokenService.  But even that I've never tried on a non-windows machine.  I'm not sure what the solution would be off the top of my head.  If you can get the refresh token ($refreshToken) manually and store is securely you can bypass that section of code

**Comment by FISHMANPET** [comment]
Unfortunately getting the Ouath token and storing it is kind of a hack, Google really wants you to request that through a browser session and keep it that way.  The code we were using relied on reading on a url generated by the oauth process which contained a key that could be used to auth.  It can still be done manually in any browser by copy pasting, I can see if I can find the instructions I used to create a personal oauth token.

The programmatic way to fix it is to create a daemon that will run and capture the requested URL, but that's a longer term fix.

**Comment by FISHMANPET** [comment]
@duorient this is the guide I've used to create an oauth refresh token: https://lazyadmin.nl/it/connect-to-google-api-with-powershell/
It's all a little confusing but but you can basically follow all those instructions, the important parts to save are the refreshtoken, the clientid, and the clientsecret.  Once you've got those you can use our Get-GOAuthTokenUser cmdlet to get an access key.  The cmdlet requires a projectID and scope but those aren't neccessary so you can put in whatever, and you'll get an access token you can use with the rest of our cmdlets
